"""add announcements

Revision ID: 5f305a5da9a2
Revises: 6fe18330c975
Create Date: 2026-08-05 09:11:20.313823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f305a5da9a2'
down_revision: Union[str, None] = '6fe18330c975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('audience', sa.Enum('ALL', 'STUDENTS', 'STAFF', 'PARENTS', name='announcement_audience'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_department_id'), 'announcements', ['department_id'], unique=False)
    op.create_index(op.f('ix_announcements_institution_id'), 'announcements', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_institution_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_department_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
