"""add institution settings and parent student links

Revision ID: 6fe18330c975
Revises: 2194352732e0
Create Date: 2026-08-05 08:39:30.547847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fe18330c975'
down_revision: Union[str, None] = '2194352732e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_settings',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('feature_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allow_self_registration', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain')
    )
    op.create_index(op.f('ix_institution_settings_institution_id'), 'institution_settings', ['institution_id'], unique=True)
    op.create_table('parent_student_links',
    sa.Column('parent_user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('MOTHER', 'FATHER', 'GUARDIAN', 'OTHER', name='parent_relationship'), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'student_id', name='uq_parent_student_link')
    )
    op.create_index(op.f('ix_parent_student_links_parent_user_id'), 'parent_student_links', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    # Extend the `audit_action` enum with ACCESS_DENIED. Same rationale as
    # the `userrole` enum extension in an earlier migration: Postgres
    # native enums require ALTER TYPE ... ADD VALUE (non-transactional,
    # hence the autocommit block); SQLite has no native enum (renders as
    # VARCHAR + CHECK), so the CHECK constraint is widened via batch
    # table rebuild instead.
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ACCESS_DENIED'")
    else:
        with op.batch_alter_table('audit_logs') as batch_op:
            batch_op.alter_column(
                'action',
                existing_type=sa.VARCHAR(length=12),
                type_=sa.Enum(
                    'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'ACCESS_DENIED',
                    name='audit_action',
                ),
                existing_nullable=False,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # See upgrade() note — Postgres cannot remove an enum value without
    # recreating the type entirely; ACCESS_DENIED is left as a valid but
    # application-unused value there. SQLite's CHECK constraint is fully
    # restored to the original 6 values.
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        with op.batch_alter_table('audit_logs') as batch_op:
            batch_op.alter_column(
                'action',
                existing_type=sa.Enum(
                    'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'ACCESS_DENIED',
                    name='audit_action',
                ),
                type_=sa.VARCHAR(length=12),
                existing_nullable=False,
            )
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_user_id'), table_name='parent_student_links')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_institution_settings_institution_id'), table_name='institution_settings')
    op.drop_table('institution_settings')
    # ### end Alembic commands ###
